name 'formatron_logstash'
version '0.1.1'
description 'Formatron Logstash cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/logstash-cookbook'
issues_url 'https://github.com/formatron/logstash-cookbook/issues'
supports 'ubuntu'
depends 'apt'
